#!/bin/bash
#----------------------------------------------------
# Slurm job script
#   for TACC Stampede2 SKX nodes
#
#----------------------------------------------------

#SBATCH -J sM1_04-28-2023_06          # Job name
#SBATCH -o sM1_04-28-2023_06.o%j       # Name of stdout output file
#SBATCH -e sM1_04-28-2023_06.e%j       # Name of stderr error file
#SBATCH -A TG-IBN140002
#SBATCH -p skx-normal   	# Queue (partition) name
#SBATCH -N 4               # Total # of nodes (must be 1 for serial)
#SBATCH -n 192               # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 03:00:00        # Run time (hh:mm:ss)
#SBATCH --mail-user=donald.doherty@actionpotential.com
#SBATCH --mail-type=all    # Send email at begin and end of job
ibrun --npernode=48 nrniv -python -mpi init.py

# ---------------------------------------------------
