#!/bin/bash
#---------------------------------------------------------
# Slurm job script
#   for ACCESS Expanse (San Diego Supercomputer Center)
#
# Parameters for 4.3 second simulation. Runtime ~10 hours
#---------------------------------------------------------

#SBATCH -J sM1_06-12-2024_01           # Job name
#SBATCH -o sM1_06-12-2024_01.o%j       # Name of stdout output file
#SBATCH -e sM1_06-12-2024_01.e%j       # Name of stderr error file
#SBATCH -A [your project identifier]
#SBATCH -p compute   	   	# Queue (partition) name
#SBATCH -N 1               	# Total # of nodes (must be 1 for serial)
#SBATCH --ntasks-per-node=64    # Total # of mpi tasks (should be 1 for serial)
#SBATCH --mem=128G
#SBATCH --export=ALL
#SBATCH -t 12:00:00		# Run time (hh:mm:ss)
#SBATCH --mail-user=[your email address]
#SBATCH --mail-type=all    	# Send email at begin and end of job
mpirun -n 64 nrniv -python -mpi init.py

# --------------------------------------------------------
