#!/bin/bash
#---------------------------------------------------------
# Slurm job script
#   for ACCESS Expanse (San Diego Supercomputer Center)
#
# Parameters for 0.3 second simulation.
#---------------------------------------------------------

#SBATCH -J sM1_03-25-2024_03           	# Job name
#SBATCH -o sM1_03-25-2024_03.o%j       	# Name of stdout output file
#SBATCH -e sM1_03-25-2024_03.e%j       	# Name of stderr error file
#SBATCH -A [your project identifier]
#SBATCH -p debug   			# Queue (partition) name
#SBATCH -N 1               	# Total # of nodes (must be 1 for serial)
#SBATCH --ntasks-per-node=64    # Total # of mpi tasks (should be 1 for serial)
#SBATCH --mem=128G
#SBATCH --export=ALL
#SBATCH -t 00:30:00        	# Run time (hh:mm:ss)
#SBATCH --mail-user=[your email address]
#SBATCH --mail-type=all    	# Send email at begin and end of job
mpirun -n 64 nrniv -python -mpi init.py

# --------------------------------------------------------
